name: Check Markdown links
on: 
  schedule:
    - cron: '0 8 * * *'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1.0.13
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'no'
