# This is a basic workflow to help you get started with Actions

name: Spell check

# Controls when the workflow will run
on:
  schedule:
    # Trigger Codespell at a scheduled time
    # * is a special character in YAML so you have to quote this string
    - cron: '30 0 * * *'
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
    paths:
      - '**.md'
  #pull_request:
  #  paths:
  #    - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job calls another reusable workflow
  Codespell_docs:
    name: Codespell (SBIE docs)
    uses: sandboxie-plus/Sandboxie/.github/workflows/codespell.yml@master
